### ISSUE TITLE
Migrate CI to GitHub Actions

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-java#765]
Similar to https://github.com/jaegertracing/jaeger/issues/2645

* [x] migrate tests steps from .travis.yml to GHA workflows #775
* [ ] migrate release steps from .travis.yml to GHA workflows -- pending #766
* [ ] make sure artifact publishing & release process are working
* [x] update README build badge 6003c01
* [x] change required checks to new GH jobs
* [x] remove .travis.yml #803

@jaegertracing/jaeger-maintainers fyi if someone has the cycles

**Comment by yurishkuro** [comment]
@Ashmita152 do yo have cycles to look at this? There's a first unfinished attempt in #766

**Comment by Ashmita152** [comment]
Sure Yuri, I will pick them.
